//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GREENWICH.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class IDEA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IDEA()
        {
            this.COMMENTs = new HashSet<COMMENT>();
            this.IDEACATEGORies = new HashSet<IDEACATEGORY>();
            this.REACTIONs = new HashSet<REACTION>();
        }
    
        public long IDEAID { get; set; }
        public Nullable<long> AUTHOR { get; set; }
        public string TITLE { get; set; }
        public string SLUG { get; set; }
        public string CONTENT { get; set; }
        public System.DateTime FIRSTCLOSUREDATE { get; set; }
        public System.DateTime FINALCLOSUREDATE { get; set; }
        public string PRIVACY { get; set; }
        public string UPLOAD { get; set; }
        public HttpPostedFileBase UploadFile { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMENT> COMMENTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IDEACATEGORY> IDEACATEGORies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REACTION> REACTIONs { get; set; }
        public virtual USER USER { get; set; }
    }
}
