//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GREENWICH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IDEACATEGORY
    {
        public long IDEACATEGORYID { get; set; }
        public Nullable<long> IDEAID { get; set; }
        public Nullable<long> IDEATAGID { get; set; }
    
        public virtual IDEA IDEA { get; set; }
        public virtual IDEATAG IDEATAG { get; set; }
    }
}
