//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GREENWICH.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GREENWICHEntities : DbContext
    {
        public GREENWICHEntities()
            : base("name=GREENWICHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COMMENT> COMMENTs { get; set; }
        public virtual DbSet<IDEA> IDEAs { get; set; }
        public virtual DbSet<IDEACATEGORY> IDEACATEGORies { get; set; }
        public virtual DbSet<IDEATAG> IDEATAGs { get; set; }
        public virtual DbSet<REACTION> REACTIONs { get; set; }
        public virtual DbSet<ROLE> ROLEs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
    }
}
