//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GREENWICH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REACTION
    {
        public long REACTIONID { get; set; }
        public Nullable<long> USERID { get; set; }
        public Nullable<long> IDEALID { get; set; }
        public string ACTIVE { get; set; }
    
        public virtual IDEA IDEA { get; set; }
        public virtual USER USER { get; set; }
    }
}
